/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaassets.gui;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr Melvin Kisten
 */
public class GUI extends javax.swing.JFrame {

    //Fields
    //Num of Assets
    private final byte ARRAY_SIZE = 5;
    //Formatting
    private DecimalFormat df = new DecimalFormat("R ###,###,###,###,###,###.00");
    //Actual Fields
    private String[] assetNum = new String[ARRAY_SIZE];
    private String[] assetName = new String[ARRAY_SIZE];
    private float[] bookValue = new float[ARRAY_SIZE];

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

        //Combo boxes
//        cbDetails.addItem("");
//        cbDetails.addItem("List all car details");
//        cbDetails.addItem("Which asset(s) costs R60 000");
        String[] string = {"", "List all car details", "Which asset(s) costs R60,000"};

        for (int i = 0; i < string.length; i++) {
            cbDetails.addItem(string[i]);
        }

        //Button group for Radio buttons
        btnGrp.add(radSum);
        btnGrp.add(radAVG);
        btnGrp.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnPrompt = new javax.swing.JButton();
        radSum = new javax.swing.JRadioButton();
        radAVG = new javax.swing.JRadioButton();
        cbDetails = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        btnPrompt.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnPrompt.setText("Prompt");
        btnPrompt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromptActionPerformed(evt);
            }
        });

        radSum.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        radSum.setText("Sum");
        radSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSumActionPerformed(evt);
            }
        });

        radAVG.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        radAVG.setText("AVG");
        radAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAVGActionPerformed(evt);
            }
        });

        cbDetails.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cbDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDetailsActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblTitle.setText("Corona Assets-GUI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radAVG)
                            .addComponent(radSum))
                        .addGap(85, 85, 85)
                        .addComponent(btnPrompt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(cbDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addComponent(btnPrompt)
                .addGap(73, 73, 73)
                .addComponent(cbDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(radSum)
                .addGap(66, 66, 66)
                .addComponent(radAVG)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromptActionPerformed
        //Prompt
        for (byte i = 0; i < ARRAY_SIZE; i++) {
            assetNum[i] = JOptionPane.showInputDialog("Enter asset number: ");

            assetName[i] = JOptionPane.showInputDialog("Enter asset name: ");

            bookValue[i] = Float.parseFloat(JOptionPane.showInputDialog("Enter asset book value:"));
        }

    }//GEN-LAST:event_btnPromptActionPerformed

    private void cbDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDetailsActionPerformed
        //Combo Box Actions
        //List all car details
        if (cbDetails.getSelectedItem().equals("List all car details")) {
            //Output
            String st = "";
            for (byte i = 0; i < ARRAY_SIZE; i++) {
                st += "\nAsset number: " + assetNum[i]
                        + "\nAsset name: " + assetName[i]
                        + "\nAsset book value: " + df.format(bookValue[i])
                        + "\n\n";
            }
            JOptionPane.showMessageDialog(null, st);

            //Answer question
        } else if (cbDetails.getSelectedItem().equals("Which asset(s) costs R60 000")) {
            JOptionPane.showMessageDialog(null, findCost(60000) + " costs R60 000");
        }
    }//GEN-LAST:event_cbDetailsActionPerformed

    private void radSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSumActionPerformed
        //Output Sum of assets
        if (radSum.isSelected()) {
            JOptionPane.showMessageDialog(null, "Sum is: " + df.format(sum()));
        }
    }//GEN-LAST:event_radSumActionPerformed

    private void radAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAVGActionPerformed
        //Output AVG of assets
        if (radAVG.isSelected()) {
            JOptionPane.showMessageDialog(null, "Average is: " + df.format(avg()));
        }
    }//GEN-LAST:event_radAVGActionPerformed

    //Answer question
    private String findCost(float num) {
        float costs = bookValue[0];
        String costsString = assetName[0];

        for (byte i = 0; i < ARRAY_SIZE; i++) {
            if (bookValue[i] == num) {

                costs = bookValue[i];
                costsString = assetName[i];
            }
        }

        if (costs != num) {
            return "Not found!";
        }
        return costsString;
    }

    //Compute Sum of assets
    private float sum() {
        float sumOfAssets = 0;
        for (byte i = 0; i < ARRAY_SIZE; i++) {
            sumOfAssets += bookValue[i];
        }
        return sumOfAssets;
    }

//Compute AVG of assets
    private float avg() {
        return sum() / ARRAY_SIZE;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JButton btnPrompt;
    private javax.swing.JComboBox<String> cbDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radAVG;
    private javax.swing.JRadioButton radSum;
    // End of variables declaration//GEN-END:variables
}
